baseurl: "https://www.engr.mun.ca/~spw2016/"
languageCode: en-us
title: Twenty-fourth International Workshop on Security Protocols
theme: bootstrap

params:
  author: SPW 2016
  location: Brno, Czech Republic
  dates: 7-8 April 2016

menu:
  main:
    - Name: Welcome
      URL: /
      Weight: -120
    - Name: Registration
      URL: https://www.fi.muni.cz/~zriha/spw2016/reg_form.php
      Weight: -115
    - Name: Organization
      Weight: -110
    - Name: Local arrangements
      Weight: -100
